import type { ImageAsset, Project } from './types'

/**
 * PORTFOLIO — real photos of РЕКОМ ГРУП work (recom.bg + the company's photo archive).
 *
 * The company has no per-object records (names, addresses, years). Titles therefore describe the
 * building and the work that is visible in the photos; location is the company's working area
 * (София и региона). Object names, years and m² are intentionally NOT invented — the fields are
 * omitted and hidden in the UI. Materials are inferred from the photos (wood-look panels → HPL,
 * metal cassettes → Al Bond); correct them here if needed.
 */
const img = (folder: string, name: string, alt: string): ImageAsset => ({ src: `images/projects/${folder}/${name}`, alt })
const AREA = { city: '' }

export const projects: Project[] = [
  {
    id: 'p-hpl-darvesen-dekor',
    slug: 'zhilishtna-sgrada-hpl-darvesen-dekor',
    title: 'Жилищна сграда с HPL фасада в дървесен декор',
    location: AREA,
    type: 'residential',
    materials: ['hpl'],
    services: ['hpl-fasadi', 'ventiliruemi-fasadi', 'fasadni-konstrukcii', 'montazh'],
    summary: 'Топла дървесна визия на цялата фасада — HPL плоскости върху вентилируема подконструкция.',
    description:
      'Многоетажна жилищна сграда, облицована изцяло с HPL плоскости в дървесен декор. Хоризонталното редене подчертава обема на сградата, а тъмните рамки на прозорците контрастират с топлия тон на облицовката.',
    challenge: 'Голяма площ с много отвори и ъгли, при които фугите и редовете на плоскостите трябва да продължават без прекъсване.',
    solution: 'Предварителен разкрой на всяка фасада и подконструкция, нивелирана по етажи, така че хоризонталните фуги да минават по цялата сграда.',
    execution: ['Замерване и разкрой', 'Монтаж на алуминиева подконструкция', 'Монтаж на HPL плоскостите', 'Детайли около прозорците и ъглите'],
    cover: img('hpl-darvesen-dekor', 'cover', 'Жилищна сграда с HPL фасада в дървесен декор'),
    gallery: [
      img('hpl-darvesen-dekor', '01', 'Фасадата от друг ъгъл'),
      img('hpl-darvesen-dekor', '02', 'Изглед от улицата'),
      img('hpl-darvesen-dekor', '03', 'Детайл на HPL облицовката'),
    ],
    featured: true,
  },
  {
    id: 'p-staklo-al-bond',
    slug: 'sgrada-steklo-i-al-bond',
    title: 'Сграда с големи остъклявания и Al Bond рамки',
    location: AREA,
    type: 'residential',
    materials: ['al-bond'],
    services: ['al-bond-montazh', 'okacheni-fasadi', 'proektirane', 'montazh'],
    summary: 'Тъмни Al Bond обрамчвания на големи стъклени повърхности — минималистична, прецизна фасада.',
    description:
      'Модерна сграда с големоформатни остъклявания, обрамчени с касети от алуминиев композитен панел в тъмен цвят. Остри ръбове и точни фуги около всеки отвор.',
    challenge: 'Касетите трябва да следват точно геометрията на дограмата, без видими разлики във фугите около стъклата.',
    solution: 'Касетите се изработват по замерване на място и се монтират след дограмата, с регулируема подконструкция.',
    execution: ['Замерване след монтажа на дограмата', 'Изработка на касетите', 'Монтаж на подконструкция', 'Монтаж и фугиране'],
    cover: img('staklo-i-al-bond', 'cover', 'Сграда с големи остъклявания и тъмни Al Bond рамки'),
    gallery: [
      img('staklo-i-al-bond', '01', 'Фасада с остъкляване по цялата височина'),
      img('staklo-i-al-bond', '02', 'Ъгъл на сградата'),
      img('staklo-i-al-bond', '03', 'Общ изглед'),
    ],
    featured: true,
  },
  {
    id: 'p-keramika-zhilishtna',
    slug: 'zhilishtna-sgrada-keramichna-fasada',
    title: 'Жилищна сграда с керамична фасада',
    location: AREA,
    type: 'residential',
    materials: ['keramika'],
    services: ['keramichni-fasadi', 'ventiliruemi-fasadi', 'fasadni-konstrukcii', 'montazh'],
    summary: 'Вентилируема фасада от светли керамични плочи с тъмни вертикални акценти.',
    description:
      'Светли керамични плочи с текстура, комбинирани с тъмни вертикални жалузи. Облицовката е монтирана като вентилируема фасада върху алуминиева подконструкция.',
    challenge: 'Комбинация на два материала и много вертикални елементи, които трябва да са в една линия по всички етажи.',
    solution: 'Обща подконструкция за плочите и вертикалните акценти, с контрол на вертикалите при всеки етаж.',
    execution: ['Монтаж на подконструкция', 'Монтаж на керамичните плочи', 'Вертикални акценти и детайли', 'Предаване на обекта'],
    cover: img('keramika-zhilishtna', 'cover', 'Завършена керамична фасада на жилищна сграда'),
    gallery: [
      img('keramika-zhilishtna', '01', 'Керамична фасада с тъмни вертикални акценти'),
      img('keramika-zhilishtna', '02', 'Фасада — общ изглед'),
      img('keramika-zhilishtna', '03', 'Детайл: керамични плочи и вертикален акцент'),
      img('keramika-zhilishtna', '04', 'Керамична облицовка около прозорците'),
      img('keramika-zhilishtna', '05', 'Фасадата по време на изпълнение'),
      img('keramika-zhilishtna', '06', 'Монтаж от скеле'),
      img('keramika-zhilishtna', '07', 'Керамични плочи на обекта'),
    ],
    featured: true,
  },
  {
    id: 'p-kompleks-hpl',
    slug: 'zhilishten-kompleks-hpl-aktsenti',
    title: 'Жилищен комплекс с HPL акценти',
    location: AREA,
    type: 'residential',
    materials: ['hpl'],
    services: ['hpl-fasadi', 'ventiliruemi-fasadi', 'montazh'],
    summary: 'Вертикални ивици и балконски акценти от HPL в топъл тон върху светли фасади.',
    description:
      'Многоетажни жилищни сгради, при които HPL плоскостите оформят вертикални ивици и обрамчват балконите. Топлият цвят разчупва големите светли повърхности.',
    execution: ['Разкрой на акцентите по фасадите', 'Монтаж на подконструкция', 'Монтаж на HPL плоскостите'],
    cover: img('kompleks-hpl-aktsenti', 'cover', 'Жилищни сгради с вертикални HPL акценти'),
    gallery: [
      img('kompleks-hpl-aktsenti', '01', 'Сградите в комплекса'),
      img('kompleks-hpl-aktsenti', '02', 'HPL акценти по балконите'),
      img('kompleks-hpl-aktsenti', '03', 'Фасада с HPL и тъмни парапети'),
    ],
    featured: true,
  },
  {
    id: 'p-sivi-al-bond',
    slug: 'zhilishtni-sgradi-sivi-al-bond-kaseti',
    title: 'Жилищни сгради със сиви Al Bond касети',
    location: AREA,
    type: 'residential',
    materials: ['al-bond', 'hpl'],
    services: ['al-bond-montazh', 'hpl-fasadi', 'montazh'],
    summary: 'Сиви касети от алуминиев композитен панел, комбинирани с дървесни HPL акценти.',
    description:
      'Серия жилищни сгради и една еднофамилна къща, облицовани със сиви касети от Al Bond. Дървесните акценти от HPL подчертават входовете, балконите и еркерите.',
    execution: ['Разкрой и изработка на касетите', 'Монтаж на подконструкция', 'Монтаж на касетите и акцентите'],
    cover: img('sivi-al-bond-kaseti', 'cover', 'Жилищна сграда със сиви Al Bond касети'),
    gallery: [
      img('sivi-al-bond-kaseti', '01', 'Сиви касети и дървесни акценти'),
      img('sivi-al-bond-kaseti', '02', 'Фасада със сиви и бежови панели'),
      img('sivi-al-bond-kaseti', '03', 'Тъмна фасада с дървесни акценти'),
      img('sivi-al-bond-kaseti', '04', 'Бяла сграда с акценти'),
      img('sivi-al-bond-kaseti', '05', 'Еднофамилна къща с фасадна облицовка'),
    ],
    featured: true,
  },
  {
    id: 'p-al-bond-targovski',
    slug: 'targovski-obekti-al-bond',
    title: 'Търговски обекти с фасади от Al Bond',
    location: AREA,
    type: 'retail',
    materials: ['al-bond'],
    services: ['al-bond-montazh', 'okacheni-fasadi', 'montazh'],
    summary: 'Фасади на търговски сгради и магазини от алуминиеви композитни панели.',
    description:
      'Облицовка на търговски сгради с Al Bond касети — от магазини с представителни входни зони до цели фасади, изпълнени при работещ обект.',
    challenge: 'Монтаж при отворен за клиенти обект, без да се затваря входът и паркингът.',
    solution: 'Работа на етапи с вишки и ограждане само на текущата зона.',
    execution: ['Замерване и изработка на касетите', 'Монтаж на подконструкция', 'Монтаж по етапи', 'Сваляне на защитното фолио'],
    cover: img('al-bond-targovski', 'cover', 'Търговски обект с фасада от Al Bond'),
    gallery: [
      img('al-bond-targovski', '01', 'Монтаж на Al Bond касети по фасадата на търговска сграда'),
      img('al-bond-targovski', '02', 'Входна зона по време на облицовката'),
      img('al-bond-targovski', '03', 'Монтаж с вишка'),
      img('al-bond-targovski', '04', 'Касети със защитно фолио'),
      img('al-bond-targovski', '05', 'Фасада по време на монтажа'),
      img('al-bond-targovski', '06', 'Търговска фасада с вертикални панели'),
      img('al-bond-targovski', '07', 'Търговска сграда по време на облицовката'),
    ],
    featured: true,
  },
  {
    id: 'p-hpl-tamen-al-bond',
    slug: 'zhilishtni-sgradi-hpl-i-tamen-al-bond',
    title: 'Жилищни сгради с HPL и тъмен Al Bond',
    location: AREA,
    type: 'residential',
    materials: ['hpl', 'al-bond'],
    services: ['hpl-fasadi', 'al-bond-montazh', 'montazh'],
    summary: 'Комбинация от дървесен HPL и тъмни композитни панели.',
    description: 'Контрастни фасади, при които топлият HPL декор се комбинира с тъмни Al Bond обрамчвания и тавани на балконите.',
    cover: img('hpl-i-tamen-al-bond', 'cover', 'Жилищна сграда с HPL и тъмен Al Bond'),
    gallery: [
      img('hpl-i-tamen-al-bond', '01', 'Фасада с дървесен декор и тъмни елементи'),
      img('hpl-i-tamen-al-bond', '02', 'Сграда с HPL облицовка'),
      img('hpl-i-tamen-al-bond', '03', 'HPL ивици между прозорците'),
    ],
  },
  {
    id: 'p-keramika-kompleks',
    slug: 'zhilishten-kompleks-keramika',
    title: 'Жилищен комплекс с керамична облицовка',
    location: AREA,
    type: 'residential',
    materials: ['keramika'],
    services: ['keramichni-fasadi', 'ventiliruemi-fasadi', 'montazh'],
    summary: 'Керамична облицовка на многоетажни жилищни сгради.',
    description: 'Облицовка на жилищни сгради с керамични фасадни плочи, изпълнена от скеле етаж по етаж.',
    cover: img('keramika-kompleks', 'cover', 'Жилищни сгради с керамична облицовка'),
    gallery: [
      img('keramika-kompleks', '01', 'Жилищни сгради — изглед от улицата'),
      img('keramika-kompleks', '02', 'Сграда в скеле по време на монтажа'),
      img('keramika-kompleks', '03', 'Горните етажи по време на монтажа'),
      img('keramika-kompleks', '04', 'Завършена фасада'),
    ],
  },
  {
    id: 'p-byala-fasada',
    slug: 'sgrada-byala-fasada-ostaklyavane',
    title: 'Сграда с бяла фасада и тераси',
    location: AREA,
    type: 'residential',
    materials: ['al-bond'],
    services: ['al-bond-montazh', 'montazh'],
    summary: 'Светли фасадни панели и обшивки на тераси около големи остъклявания.',
    description: 'Бели фасадни панели и обшивки на терасите — чиста, светла визия около големите стъклени повърхности.',
    cover: img('byala-fasada-ostaklyavane', 'cover', 'Сграда с бяла фасада и големи остъклявания'),
    gallery: [img('byala-fasada-ostaklyavane', '01', 'Сградата по време на довършителните работи')],
  },
  {
    id: 'p-obshivki',
    slug: 'obshivki-na-tavani-i-kozirki',
    title: 'Обшивки на тавани и козирки',
    location: AREA,
    type: 'residential',
    materials: ['hpl'],
    services: ['hpl-fasadi', 'montazh'],
    summary: 'Тавани на входове и тераси, облицовани с HPL в дървесен декор.',
    description: 'Обшивки на тавани под козирки, входове и тераси — дървесната визия продължава фасадата и във входната зона.',
    cover: img('obshivki-na-tavani', 'cover', 'Таван на входна зона, облицован с HPL'),
    gallery: [
      img('obshivki-na-tavani', '01', 'Монтаж на обшивка на таван'),
      img('obshivki-na-tavani', '02', 'Вертикални ламели около вход'),
    ],
  },
  {
    id: 'p-hpl',
    slug: 'hpl-fasadi-darvesen-dekor',
    title: 'Фасади от HPL с дървесен декор',
    location: AREA,
    type: 'residential',
    materials: ['hpl'],
    services: ['hpl-fasadi', 'ventiliruemi-fasadi', 'montazh'],
    summary: 'Вентилируеми фасади от HPL плоскости с топла дървесна визия.',
    description: 'HPL облицовка на жилищни сгради — монтаж на плоскостите върху подконструкция.',
    cover: img('hpl-fasadi', 'cover', 'Монтаж на HPL плоскости с дървесен декор'),
    gallery: [
      img('hpl-fasadi', '01', 'HPL облицовка по време на монтажа'),
      img('hpl-fasadi', '02', 'Ъгъл на сграда с HPL облицовка'),
      img('hpl-fasadi', '03', 'Фасада с HPL облицовка'),
    ],
  },
  {
    id: 'p-al-bond-zhilishtna',
    slug: 'zhilishtna-sgrada-al-bond',
    title: 'Жилищна сграда с акценти от Al Bond',
    location: AREA,
    type: 'residential',
    materials: ['al-bond'],
    services: ['al-bond-montazh', 'montazh'],
    summary: 'Вертикални фасадни акценти от Al Bond между прозорците.',
    description: 'Касети от алуминиев композитен панел като вертикални акценти по фасадата на жилищна сграда.',
    cover: img('al-bond-zhilishtna', 'cover', 'Жилищна сграда с вертикални акценти от Al Bond'),
    gallery: [
      img('al-bond-zhilishtna', '01', 'Al Bond акценти по фасадата'),
      img('al-bond-zhilishtna', '02', 'Фасада — общ изглед'),
    ],
  },
  {
    id: 'p-al-bond-koloni',
    slug: 'oblitsovka-na-koloni-al-bond',
    title: 'Облицовка на колони с Al Bond',
    location: AREA,
    type: 'retail',
    materials: ['al-bond'],
    services: ['al-bond-montazh', 'dostavka', 'montazh'],
    summary: 'Обшивка на колони в търговска сграда с алуминиеви композитни панели.',
    description: 'Изработка и монтаж на кръгли обшивки на колони от Al Bond в търговска зала.',
    cover: img('al-bond-koloni', 'cover', 'Монтаж на обшивка на колона от Al Bond'),
    gallery: [
      img('al-bond-koloni', '01', 'Монтаж на обшивка на колона'),
      img('al-bond-koloni', '02', 'Колони, обшити с Al Bond'),
      img('al-bond-koloni', '03', 'Завършена обшивка на колона'),
      img('al-bond-koloni', '04', 'Материал на обекта'),
      img('al-bond-koloni', '05', 'Монтаж на колоните'),
    ],
  },
]

export const getProject = (slug: string) => projects.find((p) => p.slug === slug)
export const featuredProjects = () => projects.filter((p) => p.featured)
