import type { Service } from './types'

export const services: Service[] = [
  {
    id: 's-acp',
    slug: 'al-bond-montazh',
    name: 'Al Bond / ACP фасади',
    group: 'system',
    seoTitle: 'Al Bond монтаж, Alucobond монтаж и еталбонд фасади',
    seoDescription: 'Проектиране, изработка на касети и монтаж на Al Bond / ACP / Alucobond фасади за нови сгради и реконструкции.',
    shortDescription: 'Касети от алуминиев композитен панел — проектиране, фрезоване, огъване и монтаж.',
    description:
      'Изработваме касети по проект и ги монтираме върху алуминиева подконструкция като вентилируема или окачена фасада. Поемаме целия процес: замерване, детайли, изработка и монтаж.',
    features: ['Детайлно разкрояване и номериране на касетите', 'Изработка на касети по чертеж', 'Скрит или видим монтаж', 'Подходящо за сложни форми и обшивки'],
    applications: ['Офис и търговски сгради', 'Шоуруми и бензиностанции', 'Обшивки на колони и бордове', 'Реконструкции'],
    materials: ['al-bond'],
    cover: { src: 'images/projects/al-bond-targovski/01', alt: 'Монтаж на Al Bond касети' },
    gallery: [
      { src: 'images/projects/al-bond-targovski/cover', alt: 'Търговски обект с Al Bond' },
      { src: 'images/projects/al-bond-targovski/03', alt: 'Монтаж с вишка' },
      { src: 'images/projects/al-bond-koloni/cover', alt: 'Обшивка на колони' },
    ],
  },
  {
    id: 's-hpl',
    slug: 'hpl-fasadi',
    name: 'HPL фасади',
    group: 'system',
    seoTitle: 'HPL фасади и HPL монтаж',
    seoDescription: 'Вентилируеми HPL фасади: подконструкция, разкрой и монтаж на HPL плоскости с видим или скрит крепеж.',
    shortDescription: 'Вентилируеми фасади от HPL плоскости с видим или скрит крепеж.',
    description: 'Проектираме разкроя и подконструкцията и монтираме HPL плоскости като вентилируема фасада — самостоятелно или в комбинация с алуминиеви панели.',
    features: ['Разкрой според фасадния ритъм', 'Видим или скрит монтаж', 'Комбинация с ACP и остъкляване'],
    applications: ['Жилищни сгради', 'Училища и детски градини', 'Балкони и парапети', 'Обществени сгради'],
    materials: ['hpl'],
    cover: { src: 'images/projects/hpl-fasadi/02', alt: 'HPL фасада' },
    gallery: [
      { src: 'images/projects/hpl-fasadi/cover', alt: 'HPL с дървесен декор' },
      { src: 'images/projects/hpl-fasadi/01', alt: 'Монтаж на HPL' },
    ],
  },
  {
    id: 's-ceramic',
    slug: 'keramichni-fasadi',
    name: 'Керамични фасади',
    group: 'system',
    seoTitle: 'Керамични фасади — монтаж на вентилируеми керамични облицовки',
    seoDescription: 'Монтаж на керамични фасадни плочи върху вентилируема подконструкция.',
    shortDescription: 'Керамични фасадни плочи върху вентилируема подконструкция.',
    description: 'Изпълняваме керамични фасади със скрити или видими клипси върху алуминиева подконструкция.',
    features: ['Скрит или видим крепеж', 'Прецизно нивелиране на подконструкцията'],
    applications: ['Офис сгради', 'Хотели', 'Обществени сгради', 'Цокли и партерни нива'],
    materials: ['keramika'],
    cover: { src: 'images/projects/keramika-zhilishtna/04', alt: 'Керамична фасада' },
    gallery: [
      { src: 'images/projects/keramika-zhilishtna/03', alt: 'Керамика — детайл' },
      { src: 'images/projects/keramika-kompleks/cover', alt: 'Жилищен комплекс с керамика' },
    ],
  },
  {
    id: 's-vent',
    slug: 'ventiliruemi-fasadi',
    name: 'Вентилируеми фасади',
    group: 'system',
    seoTitle: 'Вентилируеми фасади — rainscreen фасадни системи',
    seoDescription: 'Вентилируеми фасади с облицовка от Al Bond, HPL или керамика: проектиране, доставка и монтаж.',
    shortDescription: 'Облицовка, въздушна междина, изолация и подконструкция — като цялостна система.',
    description: 'Вентилируемата фасада разделя облицовката от стената с въздушна междина. Проектираме системата според материала, основата и изискванията на проекта.',
    features: ['Избор на система според основата', 'Изолация и ветрозащита по проект', 'Облицовка от всички основни материали'],
    applications: ['Нови сгради', 'Енергийно обновяване', 'Офис, жилищни и обществени сгради'],
    materials: ['al-bond', 'hpl', 'keramika'],
    cover: { src: 'images/projects/keramika-zhilishtna/01', alt: 'Вентилируема фасада' },
    gallery: [
      { src: 'images/projects/keramika-zhilishtna/06', alt: 'Монтаж на вентилируема фасада' },
    ],
  },
  // ---------- Метални конструкции  ----------
  {
    id: 's-stairs',
    slug: 'metalni-stalbishta-i-parapeti',
    name: 'Метални стълбища и парапети',
    group: 'metal',
    seoTitle: 'Метални стълбища и парапети — изработка и монтаж',
    seoDescription: 'Изработка и монтаж на външни и вътрешни метални стълбища и парапети за жилищни и търговски сгради в София и региона.',
    shortDescription: 'Външни и вътрешни стълбища, парапети за балкони и тераси.',
    description: 'Изработваме заварени метални стълбища и парапети по размер — за външни евакуационни и сервизни стълбища, балкони, тераси и стълбищни клетки. Конструкцията се изработва в цех и се монтира на обекта.',
    features: ['Изработка по размер на обекта', 'Заварени стоманени конструкции', 'Монтаж от собствен екип'],
    applications: ['Външни стълбища', 'Парапети на балкони и тераси', 'Стълбищни клетки', 'Сервизни площадки'],
    cover: { src: 'images/metal/stalbishta-i-parapeti/cover', alt: 'Външно метално стълбище' },
    gallery: [
      { src: 'images/metal/stalbishta-i-parapeti/01', alt: 'Метално стълбище' },
      { src: 'images/metal/stalbishta-i-parapeti/02', alt: 'Парапети на тераси' },
      { src: 'images/metal/stalbishta-i-parapeti/03', alt: 'Парапет на покривна тераса' },
      { src: 'images/metal/stalbishta-i-parapeti/04', alt: 'Жилищна сграда с метални парапети' },
      { src: 'images/metal/stalbishta-i-parapeti/05', alt: 'Балкони с метални парапети' },
    ],
  },
  {
    id: 's-wintergarden',
    slug: 'zimni-gradini',
    name: 'Зимни градини',
    group: 'metal',
    seoTitle: 'Зимни градини — остъклени конструкции',
    seoDescription: 'Изграждане на остъклени зимни градини и покриви на тераси — метална конструкция и остъкляване, София и региона.',
    shortDescription: 'Остъклени помещения и покриви на тераси с метална конструкция.',
    description: 'Изграждаме зимни градини и остъклени покриви на тераси — носеща метална конструкция и остъкляване, които превръщат терасата в използваемо пространство през цялата година.',
    features: ['Метална носеща конструкция', 'Остъкляване на покрив и стени', 'Решения по размер на терасата'],
    applications: ['Тераси на къщи', 'Покривни тераси', 'Заведения и търговски обекти'],
    cover: { src: 'images/metal/zimni-gradini/cover', alt: 'Зимна градина с остъклен покрив' },
    gallery: [
      { src: 'images/metal/zimni-gradini/01', alt: 'Остъклено помещение към двор' },
      { src: 'images/metal/zimni-gradini/02', alt: 'Остъклен покрив над тераса' },
      { src: 'images/metal/zimni-gradini/03', alt: 'Зимна градина — изглед отвън' },
      { src: 'images/metal/zimni-gradini/04', alt: 'Конструкция на остъклен покрив' },
      { src: 'images/metal/zimni-gradini/05', alt: 'Остъклена тераса' },
      { src: 'images/metal/zimni-gradini/06', alt: 'Метална конструкция на зимна градина' },
    ],
  },
  {
    id: 's-canopies',
    slug: 'navesi-i-kozirki',
    name: 'Навеси и козирки',
    group: 'metal',
    seoTitle: 'Навеси и козирки — метални и стъклени',
    seoDescription: 'Метални навеси, перголи и стъклени козирки за входове, тераси и паркинги — изработка и монтаж в София и региона.',
    shortDescription: 'Перголи, стъклени козирки и навеси за входове и тераси.',
    description: 'Изработваме и монтираме метални навеси, перголи и козирки със стъклено покритие — над входове, тераси и паркоместа.',
    features: ['Метална конструкция по размер', 'Стъклено или плътно покритие', 'Монтаж към фасадата или на колони'],
    applications: ['Входове на сгради', 'Тераси и дворове', 'Паркоместа', 'Търговски обекти'],
    cover: { src: 'images/metal/navesi-i-kozirki/cover', alt: 'Пергола със стъклен покрив над тераса' },
    gallery: [
      { src: 'images/metal/navesi-i-kozirki/01', alt: 'Метален навес над тераса' },
      { src: 'images/metal/navesi-i-kozirki/02', alt: 'Стъклена козирка' },
      { src: 'images/metal/navesi-i-kozirki/03', alt: 'Конструкция на навес' },
      { src: 'images/metal/navesi-i-kozirki/04', alt: 'Метален навес към сграда' },
      { src: 'images/metal/navesi-i-kozirki/05', alt: 'Стъклен покрив на навес' },
      { src: 'images/metal/navesi-i-kozirki/06', alt: 'Козирка над тераса' },
      { src: 'images/metal/navesi-i-kozirki/07', alt: 'Стъклена козирка — изглед отдолу' },
      { src: 'images/metal/navesi-i-kozirki/08', alt: 'Стъклен навес над тераса' },
    ],
  },
  {
    id: 's-halls',
    slug: 'industrialni-haleta',
    name: 'Индустриални халета',
    group: 'metal',
    seoTitle: 'Индустриални халета — метални конструкции',
    seoDescription: 'Изграждане на промишлени и складови халета с метална конструкция и сандвич панели — от основите до готовата сграда.',
    shortDescription: 'Промишлени и складови халета — метална конструкция и облицовка.',
    description: 'Изграждаме промишлени и складови халета — основи, носеща метална конструкция и облицовка на стени и покрив със сандвич панели.',
    features: ['Основи и анкериране', 'Носеща метална конструкция', 'Облицовка със сандвич панели'],
    applications: ['Складове', 'Производствени халета', 'Сервизи и работилници'],
    cover: { src: 'images/metal/industrialni-haleta/cover', alt: 'Завършено хале със сандвич панели' },
    gallery: [
      { src: 'images/metal/industrialni-haleta/01', alt: 'Хале — изглед отвътре' },
      { src: 'images/metal/industrialni-haleta/02', alt: 'Метална конструкция на хале отвътре' },
      { src: 'images/metal/industrialni-haleta/03', alt: 'Монтаж на носещата конструкция' },
      { src: 'images/metal/industrialni-haleta/04', alt: 'Колони на хале' },
      { src: 'images/metal/industrialni-haleta/05', alt: 'Конструкция на хале' },
      { src: 'images/metal/industrialni-haleta/06', alt: 'Монтаж с вишка' },
      { src: 'images/metal/industrialni-haleta/07', alt: 'Облицовка със сандвич панели' },
    ],
  },
  {
    id: 's-fences',
    slug: 'metalni-vrati-i-ogradi',
    name: 'Метални врати и огради',
    group: 'metal',
    seoTitle: 'Метални врати и огради — изработка и монтаж',
    seoDescription: 'Изработка и монтаж на метални огради, портали и врати за къщи, дворове и обекти в София и региона.',
    shortDescription: 'Огради, портали и врати по размер.',
    description: 'Изработваме и монтираме метални огради, плъзгащи и двукрили портали и врати — по размер и дизайн, съобразен със сградата.',
    features: ['Изработка по размер', 'Модерни панелни и класически огради', 'Монтаж на обекта'],
    applications: ['Къщи и дворове', 'Жилищни сгради', 'Търговски и промишлени обекти'],
    cover: { src: 'images/metal/vrati-i-ogradi/cover', alt: 'Монтаж на метална ограда' },
    gallery: [
      { src: 'images/metal/vrati-i-ogradi/01', alt: 'Метален портал' },
      { src: 'images/metal/vrati-i-ogradi/02', alt: 'Метална ограда' },
      { src: 'images/metal/vrati-i-ogradi/03', alt: 'Монтаж на ограда' },
      { src: 'images/metal/vrati-i-ogradi/04', alt: 'Панелна ограда' },
      { src: 'images/metal/vrati-i-ogradi/05', alt: 'Ковани елементи на ограда' },
    ],
  },
]

export const getService = (slug: string) => services.find((s) => s.slug === slug)
