/**
 * Typed content model. All business content lives in src/content/*.ts.
 * Anything marked `isPlaceholder` is rendered with a visible "placeholder" label
 * and must be replaced with real, verified company data before launch.
 */

export type MaterialKey = 'al-bond' | 'hpl' | 'keramika' | 'drugi'

export type BuildingType =
  | 'residential'
  | 'office'
  | 'retail'
  | 'industrial'
  | 'hotel'
  | 'public'
  | 'other'

export type ServiceKey =
  | 'al-bond-montazh'
  | 'hpl-fasadi'
  | 'keramichni-fasadi'
  | 'ventiliruemi-fasadi'
  | 'okacheni-fasadi'
  | 'fasadni-konstrukcii'
  | 'proektirane'
  | 'dostavka'
  | 'montazh'
  | 'rekonstrukciya-na-fasadi'
  | 'metalni-stalbishta-i-parapeti'
  | 'zimni-gradini'
  | 'navesi-i-kozirki'
  | 'industrialni-haleta'
  | 'metalni-vrati-i-ogradi'

import type { ArtTone } from '../lib/facadeSvg'
export type { ArtTone }

export interface ImageAsset {
  /** Path relative to /public (e.g. "images/projects/x/hero"), without extension. Real photos only. */
  src?: string
  /** Available widths generated by scripts/optimize-images.mjs */
  widths?: number[]
  alt: string
  /** Width / height ratio */
  aspect?: number
  /** Used to render a clearly-labelled placeholder until a real photo is supplied */
  tone?: ArtTone
  seed?: number
  caption?: string
}

export interface VideoAsset {
  src: string
  poster: ImageAsset
}

export interface TechnicalItem {
  label: string
  value: string
  /** Where the value comes from (manufacturer datasheet, test report …). Required for material data. */
  source?: string
}

export interface DocumentItem {
  id: string
  title: string
  kind: 'pdf' | 'dwg' | 'dxf' | 'zip' | 'link'
  category: 'specification' | 'installation' | 'cad' | 'certificate' | 'detail' | 'brochure'
  material?: MaterialKey
  /** Path relative to /public or absolute URL. Empty → shown as "очаква се". */
  href?: string
  sizeLabel?: string
  isPlaceholder?: boolean
}

export interface Project {
  id: string
  slug: string
  title: string
  /** city: '' = not provided yet (shown as a placeholder, excluded from filters) */
  location: { city: string; region?: string; country?: string }
  year?: number
  type: BuildingType
  materials: MaterialKey[]
  services: ServiceKey[]
  /** Facade area in m², only if confirmed */
  area?: number
  summary: string
  description: string
  challenge?: string
  solution?: string
  execution?: string[]
  cover: ImageAsset
  gallery: ImageAsset[]
  beforeAfter?: { before: ImageAsset; after: ImageAsset }
  technicalDetails?: TechnicalItem[]
  technicalDocuments?: DocumentItem[]
  featured?: boolean
  isPlaceholder?: boolean
}

export interface Material {
  id: string
  slug: MaterialKey
  name: string
  aka?: string[]
  shortDescription: string
  description: string
  applications: string[]
  advantages: string[]
  finishes: string[]
  colors: string[]
  formats: string[]
  /** Only verified data supplied by the company / manufacturer. Empty → placeholder notice. */
  technicalData: TechnicalItem[]
  buildingTypes: BuildingType[]
  cover: ImageAsset
  gallery: ImageAsset[]
  seoTitle: string
  seoDescription: string
}

export interface Service {
  id: string
  slug: ServiceKey
  name: string
  group: 'system' | 'process' | 'metal'
  seoTitle: string
  seoDescription: string
  shortDescription: string
  description: string
  features: string[]
  applications: string[]
  materials?: MaterialKey[]
  cover: ImageAsset
  gallery: ImageAsset[]
}

export interface Certificate {
  id: string
  title: string
  issuer: string
  kind: 'iso' | 'safety' | 'manufacturer' | 'training'
  validUntil?: string
  image?: ImageAsset
  href?: string
  isPlaceholder?: boolean
}

export interface TrustFact {
  id: string
  /** Number to animate. null → placeholder */
  value: number | null
  suffix?: string
  label: string
}
