import type { ImageAsset } from '../../content/types'
import { asset } from '../../lib/paths'
import { placeholderPath } from '../../lib/facadeSvg'

interface Props {
  image: ImageAsset
  className?: string
  /** `sizes` attribute for responsive images */
  sizes?: string
  /** Above-the-fold image: eager + high fetch priority */
  priority?: boolean
  /** Show the "placeholder" tag on generated art (default true) */
  label?: boolean | string
  imgClassName?: string
  /** Position classes for the placeholder tag */
  labelClassName?: string
}

const DEFAULT_WIDTHS = [480, 800, 1200, 1600]

/**
 * Real photo → <picture> with AVIF/WebP srcsets (generated by scripts/optimize-images.mjs),
 * lazy by default. No photo → procedural placeholder, visibly labelled.
 */
export function Media({ image, className = '', sizes = '100vw', priority, label = true, imgClassName = '', labelClassName = 'left-3 top-3' }: Props) {
  if (image.src) {
    const widths = image.widths ?? DEFAULT_WIDTHS
    const set = (ext: string) => widths.map((w) => `${asset(`${image.src}-${w}.${ext}`)} ${w}w`).join(', ')
    const fallback = asset(`${image.src}-${widths[Math.min(1, widths.length - 1)]}.webp`)
    return (
      <picture className={`block overflow-hidden bg-surface-2 ${className}`}>
        <source type="image/avif" srcSet={set('avif')} sizes={sizes} />
        <source type="image/webp" srcSet={set('webp')} sizes={sizes} />
        <img
          src={fallback}
          alt={image.alt}
          loading={priority ? 'eager' : 'lazy'}
          decoding={priority ? 'sync' : 'async'}
          fetchPriority={priority ? 'high' : 'auto'}
          className={`h-full w-full object-cover ${imgClassName}`}
        />
      </picture>
    )
  }
  const pos = /(^|\s)!?absolute(\s|$)/.test(className) ? '' : 'relative'
  return (
    <div className={`${pos} overflow-hidden bg-surface-2 ${className}`}>
      <img
        src={asset(placeholderPath(image.tone, image.seed))}
        alt={image.alt ? `${image.alt} (илюстрация)` : ''}
        loading={priority ? 'eager' : 'lazy'}
        decoding="async"
        fetchPriority={priority ? 'high' : 'auto'}
        className={`absolute inset-0 h-full w-full object-cover ${imgClassName}`}
      />
      {label && (
        <span className={`pointer-events-none absolute ${labelClassName} inline-flex items-center gap-1.5 rounded-full bg-black/55 px-2.5 py-1 text-[0.6875rem] font-semibold uppercase tracking-[0.12em] text-white backdrop-blur-sm`}>
          <span className="h-1.5 w-1.5 rounded-full bg-[#4cc2b8]" aria-hidden="true" />
          {typeof label === 'string' ? label : 'Placeholder · снимка'}
        </span>
      )}
    </div>
  )
}
